repos:

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  #  ← versão corrigida
    hooks:
      - id: isort

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
